project:
  type: book

execute:
  freeze: auto

jupyter: 
  kernelspec: 
    name: hwan
    display_name: hwan
    language: python

book:
  title: "KAIST MFE, 2024 Fall"
  author: "Kim Hyeonghwan"
  date: "2024. 9. 2."
  cover-image: cover.png
  chapters:
    - index.qmd

    - part : 머신러닝('24 가을)
      chapters: 
        - 머신러닝1.qmd
        - 머신러닝2.qmd
        - 머신러닝실습.ipynb

    - part : 딥러닝('24 가을)
      chapters: 
        - 딥러닝1.qmd     
        - 딥러닝2.qmd
        - 딥러닝실습.ipynb

    - part : 시뮬레이션 방법론('24 가을)
      chapters: 
        - 시뮬레이션1.qmd
        - 시뮬레이션2.qmd
        - 시뮬레이션실습.ipynb
        - 시뮬레이션hw1.qmd

    - part : 이자율파생상품('24 가을)
      chapters: 
        - 이자율hw1.qmd

    - part : 수치해석학('24 가을)
      chapters: 
        - 수치해석1.qmd
        - 수치해석2.qmd
        - 수치해석실습.ipynb

    - part : 금융시장 리스크관리('24 가을)
      chapters: 
        - 리스크관리1.qmd
        - 리스크관리hw1.qmd

    - part : 미시경제학('24 가을)
      chapters: 
        - 미시1.qmd
        - 미시hw1.qmd
        - 미시hw2.qmd
        - 미시hw3.qmd
        - 미시hw4.qmd
        - 미시hw5.qmd

    - part : 글로벌 지속가능회계('24 가을)
      chapters: 
        - 글로벌회계1.qmd

  downloads: pdf

code-block-bg: true
code-block-border-left: "#31BAE9"

format:
  html:
    theme: cosmo
    linestretch : 2
    code-tools: true
    code-overflow: scroll
    monofont: 'Source Code Pro'
  pdf:
    documentclass: scrreprt
    include-in-header: header.tex
    papersize: A4
    margin-bottom: 20mm
    margin-top: 15mm
    margin-left: 15mm
    margin-right: 15mm
    monofontoptions: 
      - Scale=0.8


