project:
  type: book

execute:
  freeze: auto

jupyter: 
  kernelspec: 
    name: hwan
    display_name: hwan
    language: python

book:
  title: "KAIST MFE, 2024 Fall"
  author: "Kim Hyeonghwan"
  date: "2024. 9. 2."
  cover-image: cover.png
  chapters:
    - index.qmd

    - part : 시뮬레이션 방법론('24 가을)
      chapters: 
        - simulation1.qmd
  downloads: pdf

code-block-bg: true
code-block-border-left: "#31BAE9"

format:
  html:
    theme: cosmo
    linestretch : 2
    code-tools: true
    code-overflow: scroll
    monofont: 'Source Code Pro'
  pdf:
    documentclass: scrreprt
    include-in-header: header.tex
    papersize: A4
    margin-bottom: 30mm
    margin-top: 30mm
    margin-left: 15mm
    margin-right: 15mm
    monofontoptions: 
      - Scale=0.8


