# 미시경제학 Ch1 {.unnumbered}

Demand, Supply, Elasticity

## Law of demand

가격이 상승하면 수요는 하락하고, 가격이 하락하면 수요는 증가한다

when Other things equal(ceteris paribus)

따라서, x축이 수요량이고 y축이 가격일 때 수요곡선은 우하향함

### Other things?

이는 수요곡선 자체를 변화시키는 모든 변수 일체를 의미함.

1. Income : normal goods vs. inferior goods
2. Number of buyers
3. Substitutes vs. Complements
4. Tastes

#### 1. Income

일반적인 재화는 소득이 증가하면 수요가 증가함.

즉, 수요곡선을 오른쪽으로 평행이동시킴 ***Normal Goods***

그러나, 대중교통이나 감자같은 재화는 소득이 증가하면 오히려 수요가 감소할 수 있음.

이 경우는 수요곡선을 왼쪽으로 평행이동시킴 ***Inferior Goods***

이는 재화에 따라 고정되어있지 않으며,

때로는 소득수준이 증가함에 따라 수요가 증가하는 Normal goods였다가 소득수준이 더 크게 증가하면 수요가 감소하는 Inferior goods가 되기도 함. (e.g. Hamburger)

#### 2. Substitutes vs. Complements

대체제(e.g. 맥도날드, 버거킹)는 대체관계에 있는 재화들로, 대체제의 수요가 감소하면 재화의 수요가 증가함.

즉, 대체제의 가격상승은 재화의 수요곡선을 우측 평행이동시킴

보완재(자동차, 기름)은 상호보완관계에 있는 재화로, 보완재의 수요가 증가하면 재화의 수요가 감소함. 보완재 가격상승은 수요곡선 좌측 평행이동

#### 이외의 수요곡선을 이동시키는건 매우 많을 수 있음

중요한건, 특정재화의 수요에 영향을 미치는 방법은

1. 다른 요소를 건드려서 수요곡선 자체를 이동시키거나
2. 재화의 가격을 건드려서 수요곡선 내에서 이동시키는거임

## Law of Supply

공급의 법칙

똑같음. 가격이 올라가면 공급이 늘어나고 감소하면 공급도 감소함

따라서 일반적으로 우상향하는 공급곡선이 나타남.

언제? 다른 모든 것들이 동일할 때

### 공급곡선의 이동

1. 생산가격 Input price
2. Technology
3. Number of sellers

#### 1. Input price

생산단가가 감소하면 공급은 증가함. 공급곡선 우측 이동

생산단가 증가 - 공급량 감소 - 곡선 좌측 이동

#### 2. Technology

기술수준이 상승하면 생산단가가 감소함. 공급곡선 우측이동.

a+b
a+b+c+f+g
c+f+g

c+d
c+d+b+e
b+e

subsidy expenditure 
b+c+e+f+g+h

b+c+e+f+g
-b-c-e-f-g-h
-h : dead weight loss
